# docker-compose.yml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "80:3000"
    restart: always
    # Prisma vb. varsa DB'ye ulaşması için network ya da extra_hosts ekleyebilirsin
    # depends_on: [db]
